[project]
name = "lab1-seance-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thomas", email = "thomas.buresi33@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "faker>=40.39.0",
]

[project.scripts]
lab1-seance-2 = "lab1_seance_2:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
